import type { Act, Bearing, JourneyState, Trace } from './state-machine.js';
export type Locale='zh-CN'|'en'; export const locales:readonly Locale[]=['zh-CN','en'];
export interface ChoiceCopy{label:string;cue:string;observation:string;offer:string;cost:string;uncertainty:string;responseTitle:string;response:string;enact:string}
export interface TraceCopy{label:string;cue:string;observation:string}
export interface ActCopy{name:string;title:string;situation:string;environment:string;legend:string;choices:Record<Bearing,ChoiceCopy>}
export interface LocaleCopy{
 documentTitle:string;skip:string;languageLabel:string;zhLabel:string;enLabel:string;offers:string;costs:string;unknown:string;preview:string;notCommitted:string;commit:(label:string)=>string;actCount:(act:Act)=>string;
 arrival:{kicker:string;title:string;body:string;environment:string;start:string};approach:{kicker:string;title:string;body:string;environment:string;action:string};acts:Record<Act,ActCopy>;
 evidence:{instruction:string;legend:string;traces:Record<Trace,TraceCopy>;ready:string;actionsLegend:string};travelPrompt:string;travelLegend:string;travel:Record<1|2,{beats:[{title:string;body:string;action:string},{title:string;body:string;action:string}]}>;
 final:{gatherTitle:string;gatherBody:string;gatherAction:string;commitInstruction:string;legend:string};culmination:{title:string;body:Record<Bearing,string>;action:string};ending:{kicker:string;title:string;restart:string;recapLabel:string};families:Record<'held-line'|'read-light'|'open-distance'|'woven-course',string>;scene:(state:JourneyState)=>string;announcement:(stage:string,environment:string)=>string;
}
const en:LocaleCopy={
 documentTitle:'Three Bearings',skip:'Skip to the journey',languageLabel:'Language',zhLabel:'中文',enLabel:'EN',offers:'Keeps',costs:'Gives up',unknown:'Cannot promise',preview:'Route survey',notCommitted:'not committed',commit:(l)=>`Take ${l.toLowerCase()}`,actCount:(a)=>`Act ${['I','II','III'][a-1]} · ${a} of 3`,
 arrival:{kicker:'Early light · no path behind',title:'Three Bearings',body:'Wind has erased the track behind you. Ahead, divided ground leads toward water and a distant saddle.',environment:'The first marker on divided ground',start:'Enter the landscape'},
 approach:{kicker:'Arrival',title:'Walk until the ground divides',body:'The ridge offers cover, the marker asks for time, and the open gap holds distance. None offers all three.',environment:'Ridge, marker, and open gap ahead',action:'Reach the first marker'},
 acts:{
  1:{name:'Orientation',title:'Choose how to enter',situation:'Survey each physical route. The first line you take will remain behind you—and change what can be read at the water.',environment:'Region I · divided ground in morning wind',legend:'Survey three spatial routes',choices:{
   edge:{label:'Sheltered ridge',cue:'Cover · shortened view',observation:'The ridge blocks the crosswind and everything beyond its bend.',offer:'shelter and a boundary underfoot',cost:'the long view beyond the turn',uncertainty:'what the stone hides ahead',responseTitle:'The ridge closes around you',response:'Wind drops. Your line bends out of sight, dependable nearby and unreadable farther on.',enact:'Step into the sheltered bend'},
   wait:{label:'Turning shadow',cue:'Knowledge · lost distance',observation:'The marker’s shadow is uncovering an older cross-route, one degree at a time.',offer:'a route revealed by changing light',cost:'distance while morning moves on',uncertainty:'how long the old trace will stay legible',responseTitle:'The world moves first',response:'You remain still. The shadow turns and a faint route separates from the dust.',enact:'Leave when the line appears'},
   gap:{label:'Open notch',cue:'Distance · full exposure',observation:'The notch gives an unbroken line to the water, without shelter anywhere between.',offer:'speed and the broadest sightline',cost:'the ridge’s protection',uncertainty:'what the wind will do on open ground',responseTitle:'The horizon opens',response:'The marker falls behind quickly. Wind crosses your whole body and the water flashes ahead.',enact:'Cross the exposed ground'} }},
  2:{name:'Interpretation',title:'Read what the water changed',situation:'There is no route menu here. Inspect at least two traces, compare what they imply, then choose which imperfect signal to trust.',environment:'Region II · a bright watercourse and shifting evidence',legend:'Choose an action from incomplete evidence',choices:{
   edge:{label:'Follow the quiet prints',cue:'Evidence · fading light',observation:'Trust the prints where glare withdraws.',offer:'recent signs of firm footing',cost:'light needed for the upper climb',uncertainty:'whether the water has changed since they were made',responseTitle:'The water yields small marks',response:'You wait for glare to move. A heel and two hoofprints emerge, recent but not conclusive.',enact:'Cross from print to print'},
   wait:{label:'Build a bank marker',cue:'Return line · visible position',observation:'Make evidence for the future instead of trusting what remains.',offer:'a landmark readable from both banks',cost:'warmth and time before dusk',uncertainty:'who else may follow what you build',responseTitle:'A second point stands',response:'Stone settles on stone. The new cairn catches the first marker’s light across the water.',enact:'Cross on the line between markers'},
   gap:{label:'Move with the current',cue:'Momentum · surrendered bearing',observation:'Trust the water’s easiest diagonal rather than the destination you can see.',offer:'speed through the shallowest flow',cost:'the known alignment on the far bank',uncertainty:'where the current will release you',responseTitle:'The water turns your route',response:'The current chooses each foothold. Reeds slide between you and the first marker.',enact:'Let the current carry the crossing'} }},
  3:{name:'Commitment',title:'Decide what survives you',situation:'The route, water, and saddle share one dusk view. One direct act will preserve something and surrender something else.',environment:'Region III · the final rise at dusk',legend:'Make one irreversible final commitment',choices:{
   edge:{label:'Preserve the return line',cue:'Retraceability · no farther ground',observation:'Turn the markers toward one another and remain on this side of the saddle.',offer:'a route someone can follow backward',cost:'the unseen distance beyond the rise',uncertainty:'whether return will matter more than advance',responseTitle:'The landmarks answer',response:'The two points connect through water and ridge. The way back becomes clearer than the way onward.',enact:'Preserve the line'},
   wait:{label:'Raise a signal',cue:'Shared position · exposed flame',observation:'Place a flame where another traveler—or another watcher—can find it.',offer:'a position visible to someone else',cost:'concealment in the coming dark',uncertainty:'who will answer the light',responseTitle:'A light joins the world',response:'The signal rises. For a moment every earlier landmark carries the same warm edge.',enact:'Reveal your position'},
   gap:{label:'Scatter the markers',cue:'Onward range · no return sign',observation:'Use the marker stones to cross the saddle, leaving no intact line behind.',offer:'distance while the pale seam remains',cost:'the markers that make return possible',uncertainty:'what waits beyond the dark saddle',responseTitle:'The route releases you',response:'Stone by stone, the retraceable line becomes footing. The old world drops below the saddle.',enact:'Leave the return line behind'} }}},
 evidence:{instruction:'Look closely. Two traces are enough to form an interpretation; the third may complicate it.',legend:'Inspect environmental traces',ready:'You have enough evidence to act. You may still inspect the remaining trace.',actionsLegend:'Act on your interpretation',traces:{
  drift:{label:'Silt drift',cue:'Direction without age',observation:'A crescent of silt points downstream. It could be from this morning—or last week.'},reflection:{label:'Broken reflection',cue:'Depth without footing',observation:'The sky breaks over a narrow dark band: deeper water, though its bed looks smooth.'},reeds:{label:'Bent reeds',cue:'Passage without identity',observation:'Several reeds lean toward the far bank. Wind, animal, or traveler could have pressed them.'}}},
 travelPrompt:'The route is not a Continue button. Find the bright waypoint in the landscape, inspect what changed there, then move through it.',travelLegend:'Observe and traverse the next spatial waypoint',travel:{1:{beats:[{title:'Read the descending line',body:'Beyond the first marker, the water grows from a glint into a boundary. Your chosen route remains visible behind you.',action:'Descend along the line you made'},{title:'Test the changing ground',body:'Dry stone gives way to cool silt. Your first route now arrives as evidence, not instruction.',action:'Step from stone onto the near bank'}]},2:{beats:[{title:'Look back from the climb',body:'Water falls below. Your action there changes which landmarks still align behind you.',action:'Climb with that changed alignment'},{title:'Read the lengthening shadow',body:'The basin opens into a high saddle. Morning gold has become long violet shadow.',action:'Follow the shadow to the final rise'}]}},
 final:{gatherTitle:'Bring the journey into one view',gatherBody:'Before deciding, draw the route behind you into the dusk: first marker, water crossing, and the line that connects them.',gatherAction:'Gather the visible history',commitInstruction:'The whole route is now visible. Choose once; the landscape will not offer this decision again.',legend:'Three irreversible acts'},
 culmination:{title:'The world holds the decision',body:{edge:'The return line brightens from ridge to water. The saddle remains uncrossed.',wait:'The signal climbs above the rise. Your route becomes legible from somewhere you cannot see.',gap:'The cairn comes apart beneath your feet. Behind you, separate memories replace a retraceable path.'},action:'Stand with what changed'},
 ending:{kicker:'After the commitment',title:'The route you made',restart:'Begin another journey',recapLabel:'Three decisions carried'},families:{'held-line':'You preserved a world that can be crossed twice. Its clarity was purchased with distance left unseen.','read-light':'You travelled by attending to change. What remains is not certainty, but a world made legible through patience.','open-distance':'You gave the horizon more authority than shelter. The body remembers a direction even where markers end.','woven-course':'No single bearing explains the journey. Shelter, evidence, exposure, and relinquishment remain joined in how you read the dusk.'},
 scene:(s)=>`A continuous three-region landscape at act ${s.act}; ${s.history.length} decisions persist as route, landmarks, light, and changed alignment.`,announcement:(a,e)=>`${a}. ${e}`};

const zh:LocaleCopy={...en,documentTitle:'三次定向',skip:'跳到旅程内容',languageLabel:'语言',offers:'选择留下',costs:'同时放弃',unknown:'仍无法确定',preview:'路线勘察',notCommitted:'尚未决定',commit:(l)=>`走这条路：${l}`,actCount:(a)=>`第${['一','二','三'][a-1]}幕 · 共三幕`,
 arrival:{kicker:'晨光 · 身后已无路',title:'三次定向',body:'风抹去了来路。前方地面分开，越过水道，远处是一道鞍部。',environment:'分岔地上的第一块石标',start:'走进这片地景'},approach:{kicker:'抵达',title:'走到地面分开的地方',body:'山脊能挡风，石影需要等待，缺口通向远处。没有一处能把三样都给你。',environment:'前方是山脊、石标与开阔缺口',action:'走到第一块石标'},
 acts:{
  1:{name:'辨向',title:'决定怎样进入旅程',situation:'逐一察看真实的地势。第一条路线会留在身后，也会改变你到水边以后能够读到什么。',environment:'区域一 · 晨风中的分岔地',legend:'察看三条空间路线',choices:{
   edge:{label:'山脊内侧',cue:'有遮蔽 · 视野变短',observation:'山脊挡住横风，也挡住弯道之后的一切。',offer:'近身的遮蔽与可靠边界',cost:'转弯以后的长视野',uncertainty:'岩石挡住了什么',responseTitle:'山脊收拢了路线',response:'风声低下去。脚边的边界很可靠，更远的地面却无法读取。',enact:'走进避风的弯道'},wait:{label:'转动的石影',cue:'多知道一些 · 少走一段路',observation:'石标的影子正一寸寸揭开一条旧横路。',offer:'由光线变化显出的路线',cost:'晨光向前移动时本可走出的距离',uncertainty:'旧路痕还能清楚多久',responseTitle:'世界先动了',response:'你没有动。石影转开，一道浅路从尘土里分离出来。',enact:'等路线出现再离开'},gap:{label:'迎风的缺口',cue:'走得更远 · 完全暴露',observation:'从这里能一直看见水光，中间没有任何遮蔽。',offer:'速度与最宽的视线',cost:'山脊提供的保护',uncertainty:'横风会怎样改变穿越',responseTitle:'地平线打开了',response:'石标迅速退远。风横穿全身，前方水面一闪。',enact:'穿过无遮蔽的地面'}}},
  2:{name:'判断',title:'读懂水改变了什么',situation:'这里没有第二个岔路菜单。至少察看两处痕迹，比较它们暗示的方向，再决定相信哪一个并不完整的信号。',environment:'区域二 · 亮水与不断变化的迹象',legend:'依据不完整的证据采取行动',choices:{edge:{label:'跟随静水边的脚印',cue:'得到证据 · 失去天光',observation:'相信反光退去时出现的脚印。',offer:'近期有人踩稳的迹象',cost:'翻越高地所需的剩余天光',uncertainty:'脚印以后水势是否变过',responseTitle:'水面交出了细小痕迹',response:'你等反光移开。一枚脚跟印和两只蹄印露出来，新近，却并非结论。',enact:'从一处脚印走向下一处'},wait:{label:'在岸边垒石标',cue:'留下归线 · 暴露位置',observation:'与其相信留下的证据，不如为后来制造证据。',offer:'两岸都能读到的地标',cost:'黄昏前的时间与手中暖意',uncertainty:'还会有谁循着它走来',responseTitle:'第二个点站住了',response:'石块逐一安稳。新石堆越过水面，接住第一块石标的光。',enact:'沿两块石标之间过水'},gap:{label:'顺着浅流移动',cue:'保持速度 · 放开原方向',observation:'相信水流最省力的斜线，而不是眼前看得见的目的地。',offer:'穿过最浅水势的速度',cost:'对岸已经认出的方向',uncertainty:'水流最后会把你放在哪里',responseTitle:'水把路线转开了',response:'每一处落脚都先由水势选出。芦苇滑到你与第一块石标之间。',enact:'让水流带着你过河'}}},
  3:{name:'承诺',title:'决定什么会留下',situation:'来路、水道与鞍部同时进入黄昏。你只能直接做一次：保住一样，也亲手放弃另一样。',environment:'区域三 · 黄昏中的最后高地',legend:'做出一次不可逆的最终承诺',choices:{edge:{label:'保住归路',cue:'可以折返 · 不再向前',observation:'让两处地标彼此对准，留在鞍部这一侧。',offer:'一条能在黑暗里反向跟随的路',cost:'高地以外尚未看见的距离',uncertainty:'返回是否终会比前进重要',responseTitle:'地标彼此回应',response:'两个点越过水与山脊连在一起。归路比前路更清楚了。',enact:'保住这条线'},wait:{label:'升起信号',cue:'共享位置 · 暴露火光',observation:'把火光放在别人——或别的注视者——能找到的地方。',offer:'一个能被他人读到的位置',cost:'入夜后的隐蔽',uncertainty:'谁会回应这点光',responseTitle:'世界多了一点光',response:'信号升起。片刻之间，先前每一处地标都带上同样的暖边。',enact:'让自己的位置显露'},gap:{label:'拆散地标',cue:'继续远行 · 不留归标',observation:'用石标铺过鞍部，身后不再留下完整的线。',offer:'趁浅色仍在继续前进的距离',cost:'让返回成为可能的地标',uncertainty:'暗色鞍部以后是什么',responseTitle:'路线放开了你',response:'石标一块块变成脚下的路。旧世界沉到鞍部以下。',enact:'把归路留在身后'}}}},
 evidence:{instruction:'仔细看。两处痕迹已经足以形成判断；第三处也可能让判断变得更复杂。',legend:'察看环境痕迹',ready:'证据已经足够采取行动。你仍可以查看最后一处。',actionsLegend:'依据你的判断行动',traces:{drift:{label:'淤沙弧线',cue:'有方向 · 没有年代',observation:'一道弯曲的淤沙指向下游。它可能形成于今晨，也可能是上周。'},reflection:{label:'断开的倒影',cue:'有深浅 · 没有落脚点',observation:'天空在一道窄暗带上断开：那里水更深，河床却看起来平整。'},reeds:{label:'弯倒的芦苇',cue:'有人经过 · 不知是谁',observation:'几根芦苇倒向对岸。风、动物或行者，都可能留下它们。'}}},
 travelPrompt:'这里不是“继续”按钮。先在地景里找到发亮的行程点，察看那里发生了什么变化，再从那里穿过。',travelLegend:'察看并穿过下一处空间行程点',travel:{1:{beats:[{title:'读向下延伸的路线',body:'越过第一块石标，前方水光从一点亮色长成边界。你选过的路线仍留在身后。',action:'沿自己走出的线下降'},{title:'试探正在变化的地面',body:'干燥石地变成凉湿淤泥。第一段路线到了这里，不再是指令，而成了证据。',action:'从石地踏上近岸'}]},2:{beats:[{title:'从坡上回看',body:'水面落到下方。刚才的行动改变了身后哪些地标仍能彼此对齐。',action:'带着错开的方向向上走'},{title:'读逐渐拉长的影子',body:'盆地展开成高处的鞍部。晨光的金色已经变成长长的紫影。',action:'沿影子抵达最后高地'}]}},
 final:{gatherTitle:'把整段旅程带进同一幅画面',gatherBody:'决定之前，先让身后的路线进入黄昏：第一块石标、水边的行动，以及连接它们的线。',gatherAction:'汇拢可见的来路',commitInstruction:'整条路线已经可见。只选择一次；地景不会再把这个决定交还给你。',legend:'三种不可逆的行动'},culmination:{title:'世界接住了这个决定',body:{edge:'归线从山脊亮到水边。鞍部仍没有被越过。',wait:'信号升到高地上方。你的路线开始能被看不见的远处读取。',gap:'石堆在脚下散开。身后留下的是分散的记忆，不再是可折返的路。'},action:'站在已经改变的世界里'},ending:{kicker:'承诺之后',title:'你走出的路线',restart:'重新开始一段旅程',recapLabel:'带到终点的三个决定'},families:{'held-line':'你保住了一个可以走两次的世界。它的清楚，来自那些尚未看见的远方。','read-light':'你始终在读变化。留下的不是确定答案，而是一片因耐心而变得可读的世界。','open-distance':'你把更大的权力交给地平线。地标结束以后，身体仍记得方向。','woven-course':'没有一个决定足以解释整段旅程。遮蔽、证据、暴露与放弃，仍连在你阅读黄昏的方式里。'},scene:(s)=>`同一片连续地景中的第${s.act}幕；${s.history.length}个决定以路线、地标、光线与错开的方向继续存在。`,announcement:(a,e)=>`${a}。${e}`};
export const copy:Record<Locale,LocaleCopy>={'zh-CN':zh,en}; export function localeFromBrowser(l:string):Locale{return l.toLowerCase().startsWith('zh')?'zh-CN':'en';}
const echoes:Record<Locale,{first:Record<Bearing,string>;second:Record<Bearing,string>}>= {en:{first:{edge:'Your sheltered bend makes the far-bank drift hard to see.',wait:'The shadow-line returns only when the water reflection stills.',gap:'Your long sightline ends abruptly in the reeds.'},second:{edge:'The quiet prints remain faintly visible from the climb.',wait:'The cairn answers the first marker across the basin.',gap:'The current has pulled both older landmarks out of alignment.'}},'zh-CN':{first:{edge:'避风的弯道让你难以看清对岸的淤沙。',wait:'只有水面安静时，石影教你的那条线才会重新出现。',gap:'一路跟随的长视线，在芦苇前突然断开。'},second:{edge:'静水边的脚印，从坡上仍隐约可见。',wait:'新石堆越过盆地，与第一块石标彼此回应。',gap:'水流已经把两处旧地标拉离原来的方向。'}}};
export function historyContext(locale:Locale,state:JourneyState):string{if(state.act===2&&state.history[0])return echoes[locale].first[state.history[0]];if(state.act===3&&state.history[0]&&state.history[1])return`${echoes[locale].first[state.history[0]]} ${echoes[locale].second[state.history[1]]}`;return'';}
