import './styles.css';
import {copy,historyContext,localeFromBrowser,type Locale} from './content.js';
import {historyKey,initialJourneyState,reflectionFamily,transition,worldSignature,type Act,type Bearing,type JourneyEvent,type JourneyState,type Trace} from './state-machine.js';
function required<T extends Element>(selector:string):T{const el=document.querySelector<T>(selector);if(!el)throw new Error(`Wayfinder shell is missing ${selector}.`);return el;}
const root=required<HTMLElement>('#experience'),title=required<HTMLElement>('#story-title'),kicker=required<HTMLElement>('#story-kicker'),body=required<HTMLElement>('#story-body'),stage=required<HTMLElement>('#stage-label'),environment=required<HTMLElement>('#environment-label'),sceneTitle=required<SVGTitleElement>('#scene-title'),sceneDescription=required<SVGDescElement>('#scene-description'),live=required<HTMLElement>('#route-announcement');
const routeControls=required<HTMLFieldSetElement>('#route-controls'),traceControls=required<HTMLFieldSetElement>('#trace-controls'),travelControls=required<HTMLFieldSetElement>('#travel-controls'),decisionControls=required<HTMLFieldSetElement>('#decision-controls'),tradeoff=required<HTMLElement>('#tradeoff'),echo=required<HTMLElement>('#history-echo'),recap=required<HTMLOListElement>('#journey-recap');
const primary=required<HTMLButtonElement>('#primary-action'),commitButton=required<HTMLButtonElement>('#commit-action'),restart=required<HTMLButtonElement>('#restart-action');
const routeButtons=[...routeControls.querySelectorAll<HTMLButtonElement>('button')],traceButtons=[...traceControls.querySelectorAll<HTMLButtonElement>('button')],travelButtons=[...travelControls.querySelectorAll<HTMLButtonElement>('button')],decisionButtons=[...decisionControls.querySelectorAll<HTMLButtonElement>('button')],localeButtons=[...document.querySelectorAll<HTMLButtonElement>('[data-locale]')];
let state:JourneyState=initialJourneyState;let locale:Locale=localeFromBrowser(navigator.language);let transitioning=false;let unlockTimer:number|undefined;
function show(el:HTMLElement,visible:boolean):void{el.hidden=!visible;} function chosen():Bearing|null{return state.history.at(-1)??null;}
function setPrimary(label:string,event:JourneyEvent):void{primary.textContent=label;primary.dataset.event=event;show(primary,true);}
function setTransitioning(value:boolean):void{transitioning=value;root.dataset.transitioning=String(value);for(const button of [...routeButtons,...traceButtons,...travelButtons,...decisionButtons,primary,commitButton,restart])button.disabled=value;}
function spatialDispatch(event:JourneyEvent):void{dispatch(event);setTransitioning(true);window.clearTimeout(unlockTimer);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;unlockTimer=window.setTimeout(()=>setTransitioning(false),reduced?0:900);}
function render(announce=false,preserveFocus=false):void{
 const text=copy[locale],act=text.acts[state.act],selected=state.preview??chosen();document.documentElement.lang=locale;document.title=text.documentTitle;required<HTMLElement>('#skip-link').textContent=text.skip;required<HTMLElement>('#language-switch').setAttribute('aria-label',text.languageLabel);localeButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.locale===locale)));
 root.dataset.phase=state.phase;root.dataset.act=String(state.act);root.dataset.region=state.phase==='arrival'||state.phase==='approach'||state.act===1?'one':state.act===2?'two':'three';root.dataset.history=historyKey(state);root.dataset.preview=state.preview??'none';root.dataset.signature=worldSignature(state);root.dataset.first=state.history[0]??'none';root.dataset.second=state.history[1]??'none';root.dataset.third=state.history[2]??'none';root.dataset.travelStep=String(state.travelStep);root.dataset.travelObserved=String(state.travelObserved);root.dataset.traces=state.inspectedTraces.join('-')||'none';
 sceneTitle.textContent=text.documentTitle;sceneDescription.textContent=text.scene(state);live.lang=locale;routeControls.hidden=true;traceControls.hidden=true;travelControls.hidden=true;decisionControls.hidden=true;tradeoff.hidden=true;echo.hidden=true;recap.hidden=true;primary.hidden=true;commitButton.hidden=true;restart.hidden=true;
 required<HTMLElement>('#offer-label').textContent=text.offers;required<HTMLElement>('#cost-label').textContent=text.costs;required<HTMLElement>('#unknown-label').textContent=text.unknown;
 if(state.phase==='arrival'){kicker.textContent=text.arrival.kicker;title.textContent=text.arrival.title;body.textContent=text.arrival.body;environment.textContent=text.arrival.environment;stage.textContent=text.arrival.kicker;setPrimary(text.arrival.start,'start');}
 else if(state.phase==='approach'){kicker.textContent=text.approach.kicker;title.textContent=text.approach.title;body.textContent=text.approach.body;environment.textContent=text.approach.environment;stage.textContent=text.approach.kicker;setPrimary(text.approach.action,'reach_crossing');}
 else if(state.phase==='route_survey'){
  kicker.textContent=state.preview?`${text.preview} · ${text.notCommitted}`:text.actCount(1);title.textContent=state.preview?act.choices[state.preview].label:act.title;body.textContent=state.preview?act.choices[state.preview].observation:act.situation;environment.textContent=act.environment;stage.textContent=`${text.actCount(1)} · ${act.name}`;routeControls.hidden=false;required<HTMLElement>('#route-legend').textContent=act.legend;
  routeButtons.forEach(b=>{const bearing=b.dataset.event!.slice(7)as Bearing;const choice=act.choices[bearing];b.querySelector('span')!.textContent=choice.label;b.querySelector('small')!.textContent=choice.cue;b.setAttribute('aria-pressed',String(state.preview===bearing));});
  if(state.preview){const c=act.choices[state.preview];tradeoff.hidden=false;required<HTMLElement>('#tradeoff-offer').textContent=c.offer;required<HTMLElement>('#tradeoff-cost').textContent=c.cost;required<HTMLElement>('#tradeoff-unknown').textContent=c.uncertainty;commitButton.textContent=text.commit(c.label);commitButton.dataset.event=`commit_route_${state.preview}`;show(commitButton,true);}
 }
 else if(state.phase==='evidence'){
  kicker.textContent=text.actCount(2);title.textContent=state.inspectedTraces.length?text.evidence.traces[state.inspectedTraces.at(-1)!].label:act.title;body.textContent=state.inspectedTraces.length?text.evidence.traces[state.inspectedTraces.at(-1)!].observation:text.evidence.instruction;environment.textContent=act.environment;stage.textContent=`${text.actCount(2)} · ${act.name}`;traceControls.hidden=false;required<HTMLElement>('#trace-legend').textContent=text.evidence.legend;
  traceButtons.forEach(b=>{const trace=b.dataset.event!.slice(14)as Trace,c=text.evidence.traces[trace];b.querySelector('span')!.textContent=c.label;b.querySelector('small')!.textContent=c.cue;b.setAttribute('aria-pressed',String(state.inspectedTraces.includes(trace)));});
  const context=historyContext(locale,state);if(context){echo.textContent=context;echo.hidden=false;}if(state.inspectedTraces.length>=2){echo.textContent=`${context} ${text.evidence.ready}`.trim();echo.hidden=false;renderDecisions(2);}
 }
 else if(state.phase==='final_assembly'){
  kicker.textContent=text.actCount(3);title.textContent=text.final.gatherTitle;body.textContent=state.travelStep===0?text.final.gatherBody:text.final.commitInstruction;environment.textContent=act.environment;stage.textContent=`${text.actCount(3)} · ${act.name}`;const context=historyContext(locale,state);if(context){echo.textContent=context;echo.hidden=false;}if(state.travelStep===0)setPrimary(text.final.gatherAction,'gather_history');else renderDecisions(3);
 }
 else if(state.phase==='response'&&selected){const c=act.choices[selected];kicker.textContent=text.actCount(state.act);title.textContent=c.responseTitle;body.textContent=c.response;environment.textContent=act.environment;stage.textContent=`${act.name} · ${c.label}`;setPrimary(c.enact,'enact');}
 else if(state.phase==='travel'&&state.act<3){const travelAct=state.act as 1|2,beat=text.travel[travelAct].beats[state.travelStep as 0|1];kicker.textContent=`${act.name} · Travel ${state.travelStep+1}/2`;title.textContent=state.travelObserved?beat.title:act.name;body.textContent=state.travelObserved?beat.body:text.travelPrompt;environment.textContent=act.environment;stage.textContent=text.actCount(state.act);travelControls.hidden=false;required<HTMLElement>('#travel-legend').textContent=text.travelLegend;const observe=required<HTMLButtonElement>('#travel-observe'),move=required<HTMLButtonElement>('#travel-move');observe.textContent=beat.title;move.textContent=beat.action;observe.hidden=state.travelObserved;move.hidden=!state.travelObserved;}
 else if(state.phase==='culmination'&&selected){kicker.textContent=text.actCount(3);title.textContent=text.culmination.title;body.textContent=text.culmination.body[selected];environment.textContent=act.environment;stage.textContent=`${act.name} · ${act.choices[selected].label}`;setPrimary(text.culmination.action,'reflect');}
 else {kicker.textContent=text.ending.kicker;title.textContent=text.ending.title;body.textContent=text.families[reflectionFamily(state)];environment.textContent=text.ending.recapLabel;stage.textContent=text.ending.kicker;recap.replaceChildren(...state.history.map((b,i)=>{const li=document.createElement('li');li.textContent=`${i+1}. ${text.acts[(i+1)as Act].choices[b].label}`;return li;}));recap.hidden=false;restart.textContent=text.ending.restart;restart.hidden=false;}
 if(announce){live.textContent=text.announcement(stage.textContent??'',environment.textContent??'');if(!preserveFocus)title.focus();}
}
function renderDecisions(actNumber:2|3):void{const text=copy[locale],act=text.acts[actNumber];decisionControls.hidden=false;required<HTMLElement>('#decision-legend').textContent=actNumber===2?text.evidence.actionsLegend:text.final.legend;decisionButtons.forEach(button=>{const bearing=button.dataset.bearing as Bearing,c=act.choices[bearing];button.textContent=`${c.label} · ${c.cue}`;button.dataset.event=actNumber===2?`act_on_${bearing}`:`commit_final_${bearing}`;});}
function dispatch(event:JourneyEvent):void{if(transitioning)return;const next=transition(state,event);if(next===state)return;state=next;render(true,event.startsWith('survey_')||event.startsWith('inspect_trace_'));}
document.addEventListener('click',(e)=>{const button=(e.target as Element).closest<HTMLButtonElement>('button[data-event]');if(!button)return;const event=button.dataset.event as JourneyEvent;if(event==='advance_travel'||event==='gather_history'||event==='reflect')spatialDispatch(event);else dispatch(event);});
localeButtons.forEach(button=>button.addEventListener('click',()=>{locale=button.dataset.locale as Locale;render(true,true);button.focus();}));render();
