import fs from 'node:fs/promises';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { createValidator } from '../src/schema.js';
import { fileHash, validateM43Provenance, type M43Decision } from '../src/m43-validation.js';

const read = async <T = unknown>(name: string): Promise<T> => JSON.parse(await fs.readFile(path.resolve('docs', name), 'utf8')) as T;
interface QaArtifact { sourceManifestSha256: string }
interface GateArtifact { status: string; availableHumanActions: string[]; humanEvaluation: unknown[]; bindings: { qaReportSha256: string; independentAuditSha256: string } }
describe('M4.3 provenance and generated artifacts', () => {
  it('preserves conservative human normalization and exact authorization', async () => { await expect(validateM43Provenance()).resolves.toBeUndefined(); const decision=await read<M43Decision>('wayfinder.m42r-human-replaytest-decision.json'); expect(decision.evaluations.decisionMotivation.result).toBe('partially_supported'); expect(decision.evaluations.narrativeTone.result).toBe('not_evaluated'); expect(decision.overallAction).toBe('approve_for_expansion'); expect(decision.automationApprovedExpansion).toBe(false); });
  it('preserves the desktop/mobile scope decision', async () => { const decision=await read<M43Decision>('wayfinder.m42r-human-replaytest-decision.json'); expect(decision.productRequirements).toMatchObject({supportedLocales:['zh-CN','en'],desktopSupport:'in_scope',mobileSupport:'deferred'}); });
  it('keeps historical M4.2R bindings immutable', async () => { expect(await fileHash('docs/wayfinder.m42r-human-replaytest-gate.json')).toBe('6808d55f1d68a33eba8913c92ef4b405d6fd9b8074067855f3948c97d6cba3ae'); expect(await fileHash('docs/wayfinder.m42r-source-manifest.json')).toBe('a9558f3375c742d6edace462e06cc2fb45100cf0f54510e4e41fdd14b1505a0d'); });
  it('validates all six new schema artifacts', async () => { const validator=await createValidator(); const pairs=[['m43-human-replaytest-decision','wayfinder.m42r-human-replaytest-decision.json'],['m43-human-expansion-approval','wayfinder.m43-human-expansion-approval.json'],['m43-expansion-contract','wayfinder.m43-expansion-contract.json'],['m43-source-manifest','wayfinder.m43-source-manifest.json'],['m43-qa-report','wayfinder.m43-qa-report.json'],['human-expansion-playtest-gate','wayfinder.m43-human-expansion-playtest-gate.json']] as const; for(const [schema,file] of pairs){const validate=validator.getSchema(`https://agentic-website-studio.local/schemas/${schema}.schema.json`)!;expect(validate(await read(file)),JSON.stringify(validate.errors)).toBe(true);} });
  it('binds QA and the human gate to exact generated evidence', async () => { const qa=await read<QaArtifact>('wayfinder.m43-qa-report.json');const gate=await read<GateArtifact>('wayfinder.m43-human-expansion-playtest-gate.json');expect(qa.sourceManifestSha256).toBe(await fileHash('docs/wayfinder.m43-source-manifest.json'));expect(gate.bindings.qaReportSha256).toBe(await fileHash('docs/wayfinder.m43-qa-report.json'));expect(gate.bindings.independentAuditSha256).toBe(await fileHash('docs/wayfinder.m43-independent-expansion-audit.json')); });
  it('stops exactly at the human expansion playtest', async () => { const gate=await read<GateArtifact>('wayfinder.m43-human-expansion-playtest-gate.json');expect(gate.status).toBe('pending_human_expansion_playtest');expect(gate.availableHumanActions).toEqual(['approve_for_release_readiness','request_revision','reject_expansion_direction']);expect(gate.humanEvaluation).toHaveLength(14); });
  it('contains no deployment or release configuration', async () => { const files=await fs.readdir('.');expect(files).not.toContain('vercel.json');expect(files).not.toContain('netlify.toml');expect(files).not.toContain('.github'); });
});
