import fs from'node:fs/promises';import{describe,expect,it}from'vitest';import{createValidator}from'../src/schema.js';import{fileHash,validateM43RProvenance}from'../src/m43r-validation.js';
interface FeedbackArtifact{evaluations:Record<string,{result:string}>;overallAction:string;automationVerdict:string}interface QaArtifact{sourceManifestSha256:string;independentAuditSha256:string}interface GateArtifact{status:string;bindings:{qaReportSha256:string;buildArtifacts:unknown[]};humanEvaluation:Record<string,unknown>[];availableHumanActions:string[];supportBoundary:{mobileOptimization:string}}const read=async<T>(name:string):Promise<T>=>JSON.parse(await fs.readFile(`docs/${name}`,'utf8'))as T;
describe('M4.3R provenance and generated artifacts',()=>{
 it('records the authoritative human results without inventing approval',async()=>{await expect(validateM43RProvenance()).resolves.toBeUndefined();const f=await read<FeedbackArtifact>('wayfinder.m43-human-expansion-feedback.json');expect(f.evaluations.threeBearingDifferentiation?.result).toBe('fail');expect(f.evaluations.decisionMotivation?.result).toBe('fail');expect(f.evaluations.choiceMemory?.result).toBe('pass');expect(f.evaluations.journeyPacing?.result).toBe('fail_too_short');expect(f.evaluations.sceneEvolution?.result).toBe('fail');expect(f.evaluations.motion?.result).toBe('insufficient_narrative_motion');expect(f.overallAction).toBe('request_revision');expect(f.automationVerdict).toBe('not_evaluated');});
 it('preserves every M4.3 historical artifact byte-for-byte',async()=>{const expected:Record<string,string>={'wayfinder.m43-human-expansion-approval.json':'bf20adaceffdaae3de1aa5c20be51f8e76dd697f70f1d98e757b25c4704960f8','wayfinder.m43-expansion-contract.json':'7740326702a579d9d6c1119da0ebcb6d2fb52898bff05600722c6a35417d4d2e','wayfinder.m43-source-manifest.json':'f3760177f2341bd8794b651757965807cd64d7418df78d84a70c12191b356d35','wayfinder.m43-qa-report.json':'247680b62bcf11b4bd7f01d877cb42f351130a8e4805d1f14bcb6b1ce8c45ce1','wayfinder.m43-human-expansion-playtest-gate.json':'fcdf377f39e4166d668f57d91a3327ee777c4ffb3847d8dc25f90755e676f600'};for(const[file,hash]of Object.entries(expected))expect(await fileHash(`docs/${file}`)).toBe(hash);});
 it('validates all five M4.3R schemas and artifacts',async()=>{const v=await createValidator();for(const[schema,file]of[['m43-human-expansion-feedback','wayfinder.m43-human-expansion-feedback.json'],['m43r-revision-contract','wayfinder.m43r-revision-contract.json'],['m43r-source-manifest','wayfinder.m43r-source-manifest.json'],['m43r-qa-report','wayfinder.m43r-qa-report.json'],['human-expansion-replaytest-gate','wayfinder.m43r-human-expansion-replaytest-gate.json']]as const){const validate=v.getSchema(`https://agentic-website-studio.local/schemas/${schema}.schema.json`)!;expect(validate(await read<unknown>(file)),JSON.stringify(validate.errors)).toBe(true);}});
 it('binds manifest, QA, audit, gate, and build exactly',async()=>{const qa=await read<QaArtifact>('wayfinder.m43r-qa-report.json'),gate=await read<GateArtifact>('wayfinder.m43r-human-expansion-replaytest-gate.json');expect(qa.sourceManifestSha256).toBe(await fileHash('docs/wayfinder.m43r-source-manifest.json'));expect(qa.independentAuditSha256).toBe(await fileHash('docs/wayfinder.m43r-independent-revision-audit.json'));expect(gate.bindings.qaReportSha256).toBe(await fileHash('docs/wayfinder.m43r-qa-report.json'));expect(gate.bindings.buildArtifacts).toHaveLength(3);});
 it('stops at exactly 13 unanswered human questions',async()=>{const gate=await read<GateArtifact>('wayfinder.m43r-human-expansion-replaytest-gate.json');expect(gate.status).toBe('pending_human_expansion_replaytest');expect(gate.humanEvaluation).toHaveLength(13);expect(gate.humanEvaluation.every(q=>!('answer'in q))).toBe(true);expect(gate.availableHumanActions).toEqual(['approve_for_release_readiness','request_revision','reject_expansion_direction']);});
 it('contains no deployment, release, M5, or mobile claim',async()=>{const gate=await read<GateArtifact>('wayfinder.m43r-human-expansion-replaytest-gate.json');expect(gate.supportBoundary.mobileOptimization).toBe('deferred');expect(await fs.readdir('.')).not.toEqual(expect.arrayContaining(['vercel.json','netlify.toml','.github']));});
});
