import fs from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import { copy, historyContext, locales, localeFromBrowser } from '../pilots/wayfinder/src/content.js';
import { initialJourneyState, transition, type Bearing } from '../pilots/wayfinder/src/state-machine.js';
function strings(value: unknown): string[] { if (typeof value === 'string') return [value]; if (typeof value === 'function') return []; if (value && typeof value === 'object') return Object.values(value).flatMap(strings); return []; }
describe('M4.3 content and presentation contract', () => {
  it('supports exactly zh-CN and en', () => { expect(locales).toEqual(['zh-CN', 'en']); });
  it('selects Chinese only for zh browser languages', () => { expect(localeFromBrowser('zh-Hans-CN')).toBe('zh-CN'); expect(localeFromBrowser('en-US')).toBe('en'); expect(localeFromBrowser('fr')).toBe('en'); });
  it('has complete non-placeholder content in both locales', () => { for (const locale of locales) { const values = strings(copy[locale]); expect(values.length).toBeGreaterThan(90); expect(values.every((value) => value.trim().length > 0)).toBe(true); expect(values.join(' ')).not.toMatch(/TODO|placeholder|undefined/i); } });
  it('has semantic parity across all acts and choices', () => { for (const act of [1, 2, 3] as const) for (const bearing of ['edge', 'wait', 'gap'] as Bearing[]) expect(Object.keys(copy.en.acts[act].choices[bearing])).toEqual(Object.keys(copy['zh-CN'].acts[act].choices[bearing])); });
  it('differentiates choice labels between all three acts', () => { for (const locale of locales) expect(new Set(([1, 2, 3] as const).flatMap((act) => Object.values(copy[locale].acts[act].choices).map((choice) => choice.label))).size).toBe(9); });
  it('keeps language outside serialized journey state', () => { expect(initialJourneyState).not.toHaveProperty('locale'); const state = transition(transition(initialJourneyState, 'start'), 'reach_crossing'); expect(JSON.parse(JSON.stringify(state))).toEqual(state); });
  it('conditions later situations on earlier history in both locales', () => { let edge = transition(transition(initialJourneyState,'start'),'reach_crossing'); edge = transition(transition(transition(edge,'inspect_edge'),'commit_edge'),'enact'); edge = transition(edge,'arrive'); let gap = transition(transition(initialJourneyState,'start'),'reach_crossing'); gap = transition(transition(transition(gap,'inspect_gap'),'commit_gap'),'enact'); gap = transition(gap,'arrive'); for (const locale of locales) { expect(historyContext(locale,edge)).not.toBe(historyContext(locale,gap)); expect(historyContext(locale,edge).length).toBeGreaterThan(10); } });
  it('contains no remote runtime references', async () => { const files = await Promise.all(['pilots/wayfinder/index.html','pilots/wayfinder/src/main.ts','pilots/wayfinder/src/styles.css'].map((file) => fs.readFile(file,'utf8'))); expect(files.join('\n')).not.toMatch(/https?:\/\//); });
  it('uses project-native SVG and no external creative asset tags', async () => { const html = await fs.readFile('pilots/wayfinder/index.html','utf8'); expect(html).toContain('<svg'); expect(html).not.toMatch(/<(img|audio|video|iframe)\b/i); });
  it('declares keyboard/live semantics and reduced motion', async () => { const css = await fs.readFile('pilots/wayfinder/src/styles.css','utf8'); expect(css).toContain('prefers-reduced-motion'); expect(await fs.readFile('pilots/wayfinder/index.html','utf8')).toContain('aria-live="polite"'); });
});
