import {describe,expect,it} from 'vitest';
import {actBlueprints,bearings,historyKey,initialJourneyState,isComplete,reflectionFamily,transition,worldSignature,type Bearing,type JourneyState} from '../pilots/wayfinder/src/state-machine.js';
function enter():JourneyState{return transition(transition(initialJourneyState,'start'),'reach_crossing');}
function act1(state:JourneyState,b:Bearing):JourneyState{return transition(transition(state,`survey_${b}`),`commit_route_${b}`);}
function travel(state:JourneyState):JourneyState{state=transition(state,'enact');for(let i=0;i<2;i++){state=transition(state,'observe_travel');state=transition(state,'advance_travel');}return state;}
function act2(state:JourneyState,b:Bearing):JourneyState{state=transition(state,'inspect_trace_drift');state=transition(state,'inspect_trace_reeds');return transition(state,`act_on_${b}`);}
function complete(history:readonly Bearing[]):JourneyState{let state=travel(act1(enter(),history[0]!));state=travel(act2(state,history[1]!));state=transition(state,'gather_history');state=transition(state,`commit_final_${history[2]!}`);return transition(state,'reflect');}
const histories=bearings.flatMap(a=>bearings.flatMap(b=>bearings.map(c=>[a,b,c]as const)));
describe('M4.3R deterministic differentiated journey model',()=>{
 it('requires arrival and approach before spatial survey',()=>{expect(transition(initialJourneyState,'commit_route_edge')).toBe(initialJourneyState);expect(enter().phase).toBe('route_survey');});
 it('keeps Act I survey reversible until matching route commit',()=>{const state=enter(),edge=transition(state,'survey_edge'),wait=transition(edge,'survey_wait');expect(edge.history).toEqual([]);expect(wait.preview).toBe('wait');expect(transition(wait,'commit_route_edge')).toBe(wait);});
 it('makes Act II gather evidence rather than preview routes',()=>{let state=travel(act1(enter(),'edge'));expect(state.phase).toBe('evidence');expect(transition(state,'act_on_wait')).toBe(state);state=transition(state,'inspect_trace_drift');expect(transition(state,'act_on_wait')).toBe(state);state=transition(state,'inspect_trace_reeds');expect(transition(state,'act_on_wait').history).toEqual(['edge','wait']);});
 it('does not require inspecting every trace',()=>{let state=travel(act1(enter(),'gap'));state=transition(transition(state,'inspect_trace_reflection'),'inspect_trace_reeds');expect(transition(state,'act_on_edge').phase).toBe('response');expect(state.inspectedTraces).toHaveLength(2);});
 it('makes Act III gather history before a direct irreversible commit',()=>{let state=travel(act2(travel(act1(enter(),'edge')),'wait'));expect(state.phase).toBe('final_assembly');expect(transition(state,'commit_final_gap')).toBe(state);state=transition(state,'gather_history');expect(transition(state,'commit_final_gap').phase).toBe('culmination');});
 it('uses three materially different semantic primitives and sequences',()=>{expect(new Set(Object.values(actBlueprints).map(a=>a.primitive)).size).toBe(3);expect(new Set(Object.values(actBlueprints).map(a=>a.semanticSequence.join('>'))).size).toBe(3);expect(actBlueprints[2].semanticSequence).toContain('compare_incomplete_evidence');expect(actBlueprints[3].semanticSequence).toContain('weigh_irreversible_sacrifice');});
 it('requires every option to encode opportunity, relinquishment, uncertainty, and affected dimensions',()=>{for(const act of Object.values(actBlueprints))for(const option of Object.values(act.options)){expect(option.opportunity.length).toBeGreaterThan(8);expect(option.relinquishment.length).toBeGreaterThan(8);expect(option.uncertainty.length).toBeGreaterThan(8);expect(option.affectedDimensions.length).toBeGreaterThanOrEqual(3);}});
 it('uses observe-then-move travel beats between each region',()=>{let state=act1(enter(),'wait');state=transition(state,'enact');expect(transition(state,'advance_travel')).toBe(state);state=transition(state,'observe_travel');expect(state).toMatchObject({phase:'travel',travelStep:0,travelObserved:true});state=transition(state,'advance_travel');expect(state).toMatchObject({phase:'travel',travelStep:1,travelObserved:false});state=transition(state,'observe_travel');state=transition(state,'advance_travel');expect(state).toMatchObject({phase:'evidence',act:2});});
 it('all 27 histories terminate with distinct ordered histories',()=>{const done=histories.map(complete);expect(done.every(isComplete)).toBe(true);expect(new Set(done.map(historyKey)).size).toBe(27);});
 it('all 27 histories produce deterministic final signatures',()=>{for(const h of histories)expect(worldSignature(complete(h))).toBe(worldSignature(complete(h)));expect(new Set(histories.map(h=>worldSignature(complete(h)))).size).toBe(27);});
 it('preserves Bearing I with identical later choices',()=>{const a=complete(['edge','wait','gap']),b=complete(['gap','wait','gap']);expect(a.memory).not.toEqual(b.memory);expect(worldSignature(a)).not.toBe(worldSignature(b));});
 it('rejects progression events in the wrong phase',()=>{for(const event of ['advance_travel','reflect','act_on_gap','commit_final_edge']as const)expect(transition(initialJourneyState,event)).toBe(initialJourneyState);});
 it('restart is available only after the complete reflection',()=>{expect(transition(complete(['wait','wait','wait']),'restart')).toEqual(initialJourneyState);expect(transition(enter(),'restart')).not.toEqual(initialJourneyState);});
 it('contains no random dependency',async()=>{const source=await import('node:fs/promises').then(fs=>fs.readFile('pilots/wayfinder/src/state-machine.ts','utf8'));expect(source).not.toMatch(/Math\.random|crypto\.random/);});
 it('retains bounded reflection families',()=>{const families=new Set(histories.map(h=>reflectionFamily(complete(h))));expect(families.size).toBeGreaterThan(1);expect(families.size).toBeLessThan(27);});
});
