import fs from 'node:fs/promises';import {describe,expect,it}from'vitest';import{copy,historyContext,locales,localeFromBrowser}from'../pilots/wayfinder/src/content.js';import{initialJourneyState,transition,type Bearing}from'../pilots/wayfinder/src/state-machine.js';
function strings(v:unknown):string[]{if(typeof v==='string')return[v];if(typeof v==='function')return[];if(v&&typeof v==='object')return Object.values(v).flatMap(strings);return[];}
describe('M4.3R content and presentation contract',()=>{
 it('supports exactly zh-CN and en',()=>expect(locales).toEqual(['zh-CN','en']));
 it('selects Chinese only for zh browser languages',()=>{expect(localeFromBrowser('zh-Hans-CN')).toBe('zh-CN');expect(localeFromBrowser('en-US')).toBe('en');});
 it('has complete non-placeholder authored content in both locales',()=>{for(const locale of locales){const values=strings(copy[locale]);expect(values.length).toBeGreaterThan(120);expect(values.every(v=>v.trim().length>0)).toBe(true);expect(values.join(' ')).not.toMatch(/TODO|placeholder|undefined/i);}});
 it('has semantic parity including opportunity, cost, and uncertainty',()=>{for(const act of[1,2,3]as const)for(const b of['edge','wait','gap']as Bearing[])expect(Object.keys(copy.en.acts[act].choices[b])).toEqual(Object.keys(copy['zh-CN'].acts[act].choices[b]));});
 it('authors nine differentiated decisions per locale',()=>{for(const locale of locales)expect(new Set(([1,2,3]as const).flatMap(a=>Object.values(copy[locale].acts[a].choices).map(c=>c.label))).size).toBe(9);});
 it('conditions later situations on Bearing I in both locales',()=>{const arrive=(s:typeof initialJourneyState)=>{s=transition(s,'enact');for(let i=0;i<2;i++){s=transition(s,'observe_travel');s=transition(s,'advance_travel');}return s;};let edge=transition(transition(initialJourneyState,'start'),'reach_crossing');edge=arrive(transition(transition(edge,'survey_edge'),'commit_route_edge'));let gap=transition(transition(initialJourneyState,'start'),'reach_crossing');gap=arrive(transition(transition(gap,'survey_gap'),'commit_route_gap'));for(const locale of locales){expect(historyContext(locale,edge)).not.toBe(historyContext(locale,gap));expect(historyContext(locale,edge).length).toBeGreaterThan(10);}});
 it('keeps locale outside deterministic journey state',()=>expect(initialJourneyState).not.toHaveProperty('locale'));
 it('contains no remote runtime references',async()=>{const files=await Promise.all(['pilots/wayfinder/index.html','pilots/wayfinder/src/main.ts','pilots/wayfinder/src/styles.css'].map(f=>fs.readFile(f,'utf8')));expect(files.join('\n')).not.toMatch(/https?:\/\//);});
 it('uses one project-native wide SVG world with three regions',async()=>{const html=await fs.readFile('pilots/wayfinder/index.html','utf8');expect(html).toContain('region-one');expect(html).toContain('region-two');expect(html).toContain('region-three');expect(html).not.toMatch(/<(img|audio|video|iframe)\b/i);});
 it('declares meaningful motion, embodied travel, visible convergence, locking, and reduced motion',async()=>{const css=await fs.readFile('pilots/wayfinder/src/styles.css','utf8'),main=await fs.readFile('pilots/wayfinder/src/main.ts','utf8'),html=await fs.readFile('pilots/wayfinder/index.html','utf8');expect(css).toMatch(/\.camera.*transition/);expect(css).toContain('prefers-reduced-motion');expect(main).toContain('dataset.transitioning');expect(main).toContain('travelObserved');expect(main).not.toContain('animationend');expect(html).toContain('memory-convergence');expect(html).toContain('observe_travel');expect(html).toContain('aria-live="polite"');});
});
