import fs from'node:fs/promises';import path from'node:path';import{AxeBuilder}from'@axe-core/playwright';import{expect,test,type Page}from'playwright/test';import{preview,type PreviewServer}from'vite';
const evidence=path.resolve('.tmp/wayfinder-evidence-m43r');let server:PreviewServer;type Bearing='edge'|'wait'|'gap';
const names={en:{act1:{edge:'Sheltered ridge',wait:'Turning shadow',gap:'Open notch'},act2:{edge:'Follow the quiet prints',wait:'Build a bank marker',gap:'Move with the current'},act3:{edge:'Preserve the return line',wait:'Raise a signal',gap:'Scatter the markers'}},zh:{act1:{edge:'山脊内侧',wait:'转动的石影',gap:'迎风的缺口'},act2:{edge:'跟随静水边的脚印',wait:'在岸边垒石标',gap:'顺着浅流移动'},act3:{edge:'保住归路',wait:'升起信号',gap:'拆散地标'}}}as const;
async function unlocked(page:Page):Promise<void>{await expect(page.locator('main')).toHaveAttribute('data-transitioning','false');}
async function begin(page:Page):Promise<void>{await page.goto('/');await page.getByRole('button',{name:'Enter the landscape'}).click();await page.getByRole('button',{name:'Reach the first marker'}).click();await expect(page.locator('main')).toHaveAttribute('data-phase','route_survey');}
async function travel(page:Page):Promise<void>{await page.locator('#primary-action').click();await expect(page.locator('main')).toHaveAttribute('data-phase','travel');for(let i=0;i<2;i++){await page.locator('#travel-observe').click();await expect(page.locator('main')).toHaveAttribute('data-travel-observed','true');await page.locator('#travel-move').click();await unlocked(page);}}
async function chooseAct1(page:Page,b:Bearing,locale:'en'|'zh'='en'):Promise<void>{await page.getByRole('button',{name:new RegExp(names[locale].act1[b])}).click();await expect(page.locator('#tradeoff')).toBeVisible();await page.locator('#commit-action').click();await expect(page.locator('main')).toHaveAttribute('data-phase','response');await travel(page);await expect(page.locator('main')).toHaveAttribute('data-phase','evidence');}
async function chooseAct2(page:Page,b:Bearing,locale:'en'|'zh'='en'):Promise<void>{for(const trace of locale==='en'?['Silt drift','Bent reeds']:['淤沙弧线','弯倒的芦苇'])await page.getByRole('button',{name:new RegExp(trace)}).click();await expect(page.locator('#decision-controls')).toBeVisible();await page.getByRole('button',{name:new RegExp(names[locale].act2[b])}).click();await expect(page.locator('main')).toHaveAttribute('data-phase','response');await travel(page);await expect(page.locator('main')).toHaveAttribute('data-phase','final_assembly');}
async function chooseAct3(page:Page,b:Bearing,locale:'en'|'zh'='en'):Promise<void>{await page.locator('#primary-action').click();await unlocked(page);await expect(page.locator('#decision-controls')).toBeVisible();await page.getByRole('button',{name:new RegExp(names[locale].act3[b])}).click();await expect(page.locator('main')).toHaveAttribute('data-phase','culmination');await page.locator('#primary-action').click();await unlocked(page);await expect(page.locator('main')).toHaveAttribute('data-phase','ending');}
async function journey(page:Page,h:readonly Bearing[],locale:'en'|'zh'='en'):Promise<void>{await begin(page);await chooseAct1(page,h[0]!,locale);await chooseAct2(page,h[1]!,locale);await chooseAct3(page,h[2]!,locale);}
test.beforeAll(async()=>{await fs.mkdir(evidence,{recursive:true});server=await preview({configFile:path.resolve('vite.wayfinder.config.ts')});});test.afterAll(async()=>server.close());
for(const viewport of[{name:'compact',width:1024,height:768},{name:'standard',width:1440,height:900},{name:'wide',width:1920,height:1080}])test(`${viewport.name} desktop completes the full differentiated journey`,async({page})=>{await page.setViewportSize(viewport);await journey(page,['edge','wait','gap']);await expect(page.locator('#journey-recap li')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:path.join(evidence,`${viewport.name}-ending.png`),fullPage:true});});
test('representative histories retain distinct signatures',async({page})=>{test.setTimeout(90_000);const histories:Bearing[][]=[['edge','edge','edge'],['wait','wait','wait'],['gap','gap','gap'],['edge','gap','wait'],['gap','edge','wait']],signatures=new Set<string>();for(const h of histories){await journey(page,h);signatures.add((await page.locator('main').getAttribute('data-signature'))!);await page.locator('#restart-action').click();}expect(signatures.size).toBe(histories.length);});
test('three acts expose different controls, regions, and visible final convergence',async({page})=>{await begin(page);await expect(page.locator('#route-controls')).toBeVisible();await expect(page.locator('#trace-controls')).toBeHidden();await chooseAct1(page,'edge');await expect(page.locator('main')).toHaveAttribute('data-region','two');await expect(page.locator('#trace-controls')).toBeVisible();await page.screenshot({path:path.join(evidence,'act-2-watercourse.png')});await chooseAct2(page,'wait');await expect(page.locator('main')).toHaveAttribute('data-region','three');await expect(page.locator('#route-controls')).toBeHidden();await page.locator('#primary-action').click();await unlocked(page);await expect(page.locator('.memory-convergence')).toHaveCSS('opacity','0.9');await page.screenshot({path:path.join(evidence,'act-3-gathered-history.png')});});
test('Bearing I remains visibly different later with identical II',async({page})=>{async function later(first:Bearing){await journeyToAct3(page,first,'wait');const result=[await page.locator('main').getAttribute('data-first'),await page.locator('#history-echo').innerText(),await page.locator('.route-1.'+first).getAttribute('style'),await page.locator('main').getAttribute('data-signature')];await page.reload();return result;}async function journeyToAct3(p:Page,first:Bearing,second:Bearing){await begin(p);await chooseAct1(p,first);await chooseAct2(p,second);}const edge=await later('edge'),gap=await later('gap');expect(edge[0]).not.toBe(gap[0]);expect(edge[1]).not.toBe(gap[1]);expect(edge[3]).not.toBe(gap[3]);});
test('language switching preserves evidence, history, phase, and camera region',async({page})=>{await begin(page);await chooseAct1(page,'wait');await page.getByRole('button',{name:'Silt drift'}).click();const signature=await page.locator('main').getAttribute('data-signature');await page.getByRole('button',{name:'中文'}).click();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await expect(page.locator('main')).toHaveAttribute('data-phase','evidence');await expect(page.locator('main')).toHaveAttribute('data-traces','drift');await expect(page.locator('main')).toHaveAttribute('data-signature',signature!);await page.getByRole('button',{name:/弯倒的芦苇/}).click();await page.getByRole('button',{name:/顺着浅流移动/}).click();await travel(page);await expect(page.locator('main')).toHaveAttribute('data-region','three');await page.getByRole('button',{name:'EN'}).click();await expect(page.locator('html')).toHaveAttribute('lang','en');});
test('normal motion travels, locks input, and settles without animation events',async({page})=>{await begin(page);await page.getByRole('button',{name:/Open notch/}).click();await page.locator('#commit-action').click();await page.locator('#primary-action').click();await page.locator('#travel-observe').click();await page.locator('#travel-move').click();await expect(page.locator('main')).toHaveAttribute('data-transitioning','true');expect(await page.locator('.camera').evaluate(el=>getComputedStyle(el).transitionDuration)).not.toBe('0s');await expect(page.locator('#travel-move')).toBeDisabled();await unlocked(page);await expect(page.locator('main')).toHaveAttribute('data-travel-step','1');});
test('reduced motion bypasses locks quickly but preserves spatial progress and memory',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await journey(page,['gap','wait','edge']);await expect(page.locator('.route-1.gap')).toHaveCSS('opacity','0.94');await expect(page.locator('.route-2.wait')).toHaveCSS('opacity','0.94');await expect(page.locator('.route-3.edge')).toHaveCSS('opacity','0.94');await expect(page.locator('main')).toHaveAttribute('data-region','three');});
test('keyboard completes all three distinct interaction primitives',async({page})=>{await begin(page);await page.getByRole('button',{name:/Turning shadow/}).focus();await page.keyboard.press('Enter');await page.locator('#commit-action').focus();await page.keyboard.press('Enter');await travel(page);for(const name of['Silt drift','Bent reeds']){await page.getByRole('button',{name:new RegExp(name)}).focus();await page.keyboard.press('Enter');}await page.getByRole('button',{name:/Build a bank marker/}).focus();await page.keyboard.press('Enter');await travel(page);await page.locator('#primary-action').focus();await page.keyboard.press('Enter');await unlocked(page);await page.getByRole('button',{name:/Raise a signal/}).focus();await page.keyboard.press('Enter');await page.locator('#primary-action').focus();await page.keyboard.press('Enter');await unlocked(page);await expect(page.locator('main')).toHaveAttribute('data-phase','ending');});
test('representative bilingual states have no serious or critical axe violations',async({page})=>{const scan=async()=>expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);await page.goto('/');await scan();await begin(page);await scan();await page.getByRole('button',{name:'中文'}).click();await scan();});
test('runtime is local, error-free, and deterministic',async({page,browser})=>{const external:string[]=[],errors:string[]=[];page.on('request',r=>{if(new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());});page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('pageerror',e=>errors.push(e.message));await journey(page,['edge','gap','wait']);expect(external).toEqual([]);expect(errors).toEqual([]);async function run(){const p=await browser.newPage();await journey(p,['wait','gap','edge']);const result=[await p.locator('main').getAttribute('data-signature'),await p.locator('#story-body').innerText(),await p.locator('#journey-recap').innerText()];await p.close();return result;}expect(await run()).toEqual(await run());});
