import AjvModule from 'ajv';
import fs from 'node:fs/promises';
import path from 'node:path';
// @ts-expect-error Node's strip-types runner requires the explicit local TypeScript extension.
import { fileHash, readJson, sha256, validateM43Provenance, type M43Approval, type M43Contract, type M43Decision } from './m43-validation.ts';

const root = process.cwd();
const output = async (relative: string, value: unknown): Promise<string> => { const body = `${JSON.stringify(value, null, 2)}\n`; await fs.writeFile(path.resolve(root, relative), body, 'utf8'); return sha256(body); };
const binding = async (id: string, relative: string) => ({ id, path: relative, sha256: await fileHash(path.resolve(root, relative)) });
const sourcePaths = [
  'package.json','package-lock.json','README.md','pilots/wayfinder/index.html','pilots/wayfinder/src/content.ts','pilots/wayfinder/src/main.ts','pilots/wayfinder/src/state-machine.ts','pilots/wayfinder/src/styles.css','pilots/wayfinder/src/vite-env.d.ts','playwright.wayfinder.config.ts','vite.wayfinder.config.ts','vitest.config.ts','tsconfig.json','src/schema.ts','src/m43-validation.ts','src/m43-artifacts.ts','tests/wayfinder-state.test.ts','tests/wayfinder-contract.test.ts','tests/wayfinder-e2e/wayfinder.spec.ts','tests/m42r-artifacts.test.ts','tests/m43-artifacts.test.ts','schemas/m43-human-replaytest-decision.schema.json','schemas/m43-human-expansion-approval.schema.json','schemas/m43-expansion-contract.schema.json','schemas/m43-source-manifest.schema.json','schemas/m43-qa-report.schema.json','schemas/human-expansion-playtest-gate.schema.json','docs/wayfinder.m42r-human-replaytest-decision.json','docs/wayfinder.m43-human-expansion-approval.json','docs/wayfinder.m43-expansion-contract.json'
];
await validateM43Provenance();
const decision = await readJson<M43Decision>('docs/wayfinder.m42r-human-replaytest-decision.json'); const approval = await readJson<M43Approval>('docs/wayfinder.m43-human-expansion-approval.json'); const contract = await readJson<M43Contract>('docs/wayfinder.m43-expansion-contract.json');
interface ExpansionAudit { verdict: 'pass' | 'pass_with_warnings' | 'fail'; readyForHumanExpansionPlaytest: boolean; warnings: unknown[] }
const auditPath = 'docs/wayfinder.m43-independent-expansion-audit.json'; const audit = await readJson<ExpansionAudit>(auditPath); if (audit.verdict === 'fail' || audit.readyForHumanExpansionPlaytest !== true) throw new Error('Independent audit blocks the human expansion playtest gate.');
const sourceFiles = await Promise.all(sourcePaths.map(async (relative) => ({ path: relative, sha256: await fileHash(path.resolve(root, relative)) })));
const buildDir = path.resolve(root,'.tmp/wayfinder-dist'); const built: string[]=[]; async function walk(dir:string):Promise<void>{for(const entry of await fs.readdir(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())await walk(full);else built.push(full);}} await walk(buildDir);
const buildArtifacts = await Promise.all(built.sort().map(async (full) => ({ path: path.relative(root,full).replaceAll('\\','/'), sha256: await fileHash(full), bytes: (await fs.stat(full)).size })));
const creativePaths = ['pilots/wayfinder/index.html','pilots/wayfinder/src/content.ts','pilots/wayfinder/src/main.ts','pilots/wayfinder/src/styles.css']; const creativeAssets = await Promise.all(creativePaths.map(async (relative)=>({path:relative,sha256:await fileHash(relative),provenanceClass:'project_native',rightsStatus:'project_owned_original'})));
const dependencyNames=['vite','playwright','@axe-core/playwright'] as const; const roles={vite:'build_dev_only',playwright:'test_dev_only','@axe-core/playwright':'test_dev_only'} as const; const dependencies=await Promise.all(dependencyNames.map(async(name)=>{const metadata=await readJson<{version:string;license:string}>(path.resolve('node_modules',name,'package.json'));return{name,version:metadata.version,license:metadata.license,role:roles[name]};}));
const jsBytes=buildArtifacts.filter((a)=>a.path.endsWith('.js')).reduce((n,a)=>n+a.bytes,0); const cssBytes=buildArtifacts.filter((a)=>a.path.endsWith('.css')).reduce((n,a)=>n+a.bytes,0); const totalBytes=buildArtifacts.reduce((n,a)=>n+a.bytes,0);
const manifest={schemaVersion:'1.0.0',manifestId:'manifest_wayfinder_m43_full_01',projectId:'project_wayfinder',selectedConceptId:'concept_three_bearings',bindings:{humanReplayDecision:await binding(decision.decisionId,'docs/wayfinder.m42r-human-replaytest-decision.json'),humanExpansionApproval:await binding(approval.approvalId,'docs/wayfinder.m43-human-expansion-approval.json'),expansionContract:await binding(contract.contractId,'docs/wayfinder.m43-expansion-contract.json'),m42rSourceManifest:contract.bindings.m42rSourceManifest,m42rReplaytestGate:contract.bindings.m42rReplaytestGate,implementationBaseline:'139d3aa335080a856cc9977bb0017913b3fa6375'},sourceFiles,creativeAssets,dependencies,buildArtifacts,runtimeAssetBytes:{javascript:jsBytes,css:cssBytes,totalAuthoredBuild:totalBytes}};
const sourceManifestSha256=await output('docs/wayfinder.m43-source-manifest.json',manifest); const independentAuditSha256=await fileHash(auditPath);
const result=(evidence:string,status:'pass'|'pass_with_warnings'='pass')=>({result:status,evidence});
const qa={schemaVersion:'1.0.0',reportId:'qa_wayfinder_m43_full_01',projectId:'project_wayfinder',sourceManifestSha256,independentAuditSha256,overallResult:audit.verdict==='pass'?'pass':'pass_with_warnings',testCounts:{focusedModelAndContent:26,productionBrowser:11,allDecisionHistories:27,desktopViewports:3},categories:{expansionContract:result('Human authorization, three acts, state model, locales, desktop boundary, originality, QA, and human gate validate.'),stateMachine:result('Exactly three commits; reversible preview; irreversible commit; safe invalid events; canonical restart.'),all27Histories:result('All 27 ordered histories are valid, terminate, and produce deterministic complete signatures.'),historyInfluence:result('Earlier choices alter later memory, explicit route marks, and bilingual situation context; full representation encodes all three positions.'),bilingualCompleteness:result('Typed zh-CN/en content has complete keys, no placeholders, and nine differentiated labels per locale.'),languagePreservation:result('Mid-preview and post-Bearing-II switching preserves act, preview/history/signature and updates html lang, accessible names, and live language.'),desktopMatrix:result('Complete production journeys pass at 1024x768, 1440x900, and 1920x1080 without critical overlap or horizontal overflow.'),keyboard:result('Keyboard-only journey covers observation, preview, commit, continuation, locale switch, ending, and restart.'),reducedMotion:result('All three route memories and state transitions remain legible without transition dependence.'),accessibilityAutomatedScan:result('Representative English and Chinese states have no serious or critical axe violations.','pass_with_warnings'),runtimeNetworkIsolation:result('No runtime request leaves 127.0.0.1.'),consolePageErrors:result('No console errors or unhandled page errors.'),deterministicReplay:result('Identical production-browser histories emit identical signature, ending, and recap.'),sourceProvenance:result('All creative source is project-native; build and sources are SHA-256 bound.'),independentAudit:result(`Independent audit verdict ${audit.verdict}; readyForHumanExpansionPlaytest true.`,audit.verdict==='pass'?'pass':'pass_with_warnings')},warnings:[...audit.warnings,'Automated accessibility scanning is representative and does not establish complete WCAG conformance.','The 5–8 minute pacing target and genuine decision motivation remain human-only judgments.'],humanOnlyLimitations:['Automation cannot establish felt deliberation, overall journey coherence, naturalness for every bilingual reader, aesthetic quality, or release readiness. Mobile optimization is intentionally deferred.']};
const qaReportSha256=await output('docs/wayfinder.m43-qa-report.json',qa);
const questions=[['overall_journey','Did the experience now feel like one complete short journey?'],['three_bearing_differentiation','Did Bearing I, II and III feel like genuinely different decision moments rather than repeated mechanics?'],['decision_motivation','Did at least some choices cause real hesitation or preference?'],['choice_memory','Could you feel previous choices changing later situations?'],['agency','Did the final experience feel shaped by your journey rather than by a predetermined sequence?'],['world_continuity','Did it remain one evolving world?'],['pacing','Did the complete experience feel too short, appropriate, or too long?'],['visual_coherence','Does the expanded version still feel like an intentional interactive work?'],['chinese_quality','Does zh-CN feel natural and authored rather than translated?'],['english_quality','Does English remain natural and coherent?'],['language_switching','Does switching language preserve immersion and state?'],['desktop_experience','Does it work well at normal laptop and desktop widths? No phone evaluation is required.'],['ending','Did the final reflection feel connected to the whole journey without over-explaining it?'],['overall_action','Approve for release readiness, request revision, or reject the expansion direction?']].map(([dimension,question])=>({dimension,question}));
const gate={schemaVersion:'1.0.0',gateId:'expansion_playtest_gate_wayfinder_m43_full_01',projectId:'project_wayfinder',selectedConceptId:'concept_three_bearings',status:'pending_human_expansion_playtest',bindings:{humanExpansionApprovalSha256:await fileHash('docs/wayfinder.m43-human-expansion-approval.json'),expansionContractSha256:await fileHash('docs/wayfinder.m43-expansion-contract.json'),sourceManifestSha256,qaReportSha256,independentAuditSha256,buildArtifacts},preview:{command:'npm run wayfinder:preview',address:'http://127.0.0.1:4173',termination:'Press Ctrl+C in the preview terminal.'},supportBoundary:{desktop:'supported',desktopViewports:['1024x768','1440x900','1920x1080'],mobileOptimization:'deferred_by_human_decision'},automatedQaEstablished:['All 27 deterministic histories terminate and retain complete choice memory.','Both locales and state-preserving switching pass focused and browser tests.','Supported desktop, keyboard, reduced motion, representative axe, local network, runtime errors, replay, provenance, and independent audit pass without a blocking verdict.'],knownWarnings:qa.warnings,humanEvaluation:questions,availableHumanActions:['approve_for_release_readiness','request_revision','reject_expansion_direction']};
await output('docs/wayfinder.m43-human-expansion-playtest-gate.json',gate);
const Ajv=AjvModule.default; const ajv=new Ajv({allErrors:true,strict:true}); for(const [name,value] of [['m43-source-manifest',manifest],['m43-qa-report',qa],['human-expansion-playtest-gate',gate]] as const){const schema=await readJson<object>(path.resolve('schemas',`${name}.schema.json`));const validate=ajv.compile(schema);if(!validate(value))throw new Error(`${name}: ${ajv.errorsText(validate.errors)}`);}
console.log(`M4.3 artifacts generated and validated; source manifest ${sourceManifestSha256}; runtime bytes JS=${jsBytes} CSS=${cssBytes} total=${totalBytes}`);
