import{createHash}from'node:crypto';import fs from'node:fs/promises';import path from'node:path';
export function sha256(value:Uint8Array|string):string{return createHash('sha256').update(value).digest('hex');}export async function fileHash(file:string):Promise<string>{return sha256(await fs.readFile(file));}export async function readJson<T=Record<string,unknown>>(file:string):Promise<T>{return JSON.parse(await fs.readFile(file,'utf8'))as T;}export async function assertBinding(binding:{path:string;sha256:string}):Promise<void>{const actual=await fileHash(path.resolve(binding.path));if(actual!==binding.sha256)throw new Error(`Hash mismatch for ${binding.path}: ${actual}`);}
interface Feedback{evaluations:Record<string,{result:string;humanStatement:string;normalization:string}>;overallAction:string;automationVerdict:string;immutability:{historicalArtifact:boolean}}
interface Contract{bindings:Record<string,{path:string;sha256:string}>;acts:{primitive:string;sequence:string[]}[];tradeoffContract:{requiredPerOption:string[]};journey:{targetFirstPlayMinutes:string;artificialDelays:boolean;regions:string[]};motion:{reducedMotionParity:boolean;animationEndDependency:boolean};preservation:{orderedChoiceHistory:boolean;all27Histories:boolean};humanGate:{requiredStatus:string;automationMayAnswerQuestions:boolean}}
export async function validateM43RProvenance():Promise<void>{
 const feedback=await readJson<Feedback>('docs/wayfinder.m43-human-expansion-feedback.json'),contract=await readJson<Contract>('docs/wayfinder.m43r-revision-contract.json');
 const expected={threeBearingDifferentiation:'fail',decisionMotivation:'fail',choiceMemory:'pass',journeyPacing:'fail_too_short',sceneEvolution:'fail',motion:'insufficient_narrative_motion'};for(const[k,v]of Object.entries(expected))if(feedback.evaluations[k]?.result!==v)throw new Error(`M4.3 human feedback mismatch: ${k}`);
 if(feedback.overallAction!=='request_revision'||feedback.automationVerdict!=='not_evaluated'||!feedback.immutability.historicalArtifact)throw new Error('M4.3 feedback action or immutability invalid.');
 for(const binding of Object.values(contract.bindings))await assertBinding(binding);
 if(new Set(contract.acts.map(a=>a.primitive)).size!==3||new Set(contract.acts.map(a=>a.sequence.join('>'))).size!==3)throw new Error('Act primitives or sequences are not differentiated.');
 if(JSON.stringify(contract.tradeoffContract.requiredPerOption)!==JSON.stringify(['opportunity','relinquishment','uncertainty','affectedWorldDimensions']))throw new Error('Tradeoff contract incomplete.');
 if(contract.journey.targetFirstPlayMinutes!=='5-8'||contract.journey.artificialDelays||contract.journey.regions.length!==3)throw new Error('Journey pacing contract invalid.');
 if(!contract.motion.reducedMotionParity||contract.motion.animationEndDependency||!contract.preservation.orderedChoiceHistory||!contract.preservation.all27Histories)throw new Error('Motion or memory preservation contract invalid.');
 if(contract.humanGate.requiredStatus!=='pending_human_expansion_replaytest'||contract.humanGate.automationMayAnswerQuestions)throw new Error('Human re-playtest gate boundary invalid.');
}
